export enum LandlordStatus {
  NEW = 'NEW',
  'AWAITING_VERIFICATION' = 'AWAITING_VERIFICATION',
  APPROVED = 'APPROVED',
  UPDATE_NEEDED = 'UPDATE_NEEDED',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
}
