export enum HotelType {
  HOTEL = 'HOTEL',
  HOSTEL = 'HOSTEL',
  MOTEL = 'MOTEL',
  GUEST_HOUSE = 'GUEST_HOUSE',
  APARTMENT = 'APARTMENT',
  VILLA = 'VILLA',
  COTTAGE = 'COTTAGE',
  MOBILE_HOME = 'MOBILE_HOME',
  BOARDING_HOUSE = 'BOARDING_HOUSE',
  CAMPING = 'CAMPING',
}
